insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'autumn clothes', 2, 'F', 'CUSTOM', 240);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Singlet', 'summer clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'autumn clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cropped sweaters', 'winter clothes', 4, 'F', 'CUSTOM', 215);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Mittens', 'autumn clothes', 3, 'M', 'CUSTOM', 244);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'autumn clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Gloves', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'winter clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cropped sweaters', 'autumn clothes', 3, 'F', 'CUSTOM', 196);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'summer clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'winter clothes', 4, 'F', 'CUSTOM', 47);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'autumn clothes', 1, 'M', 'CUSTOM', 150);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'winter clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'summer clothes', 2, 'M', 'CUSTOM', 136);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'winter clothes', 3, 'F', 'CUSTOM', 75);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'autumn clothes', 1, 'M', 'CUSTOM', 44);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'summer clothes', 5, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Hawaiian shirt', 'summer clothes', 3, 'M', 'CUSTOM', 115);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'autumn clothes', 3, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cropped sweaters', 'winter clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Singlet', 'autumn clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Gloves', 'winter clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Down vest', 'summer clothes', 2, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'summer clothes', 5, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'winter clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'summer clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'summer clothes', 4, 'F', 'CUSTOM', 174);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'summer clothes', 4, 'F', 'CUSTOM', 214);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'winter clothes', 1, 'M', 'CUSTOM', 125);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'winter clothes', 2, 'F', 'CUSTOM', 204);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'winter clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'summer clothes', 2, 'M', 'CUSTOM', 191);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Mittens', 'summer clothes', 4, 'F', 'CUSTOM', 150);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'summer clothes', 5, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Mittens', 'summer clothes', 3, 'F', 'CUSTOM', 255);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Singlet', 'autumn clothes', 4, 'M', 'CUSTOM', 52);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Mittens', 'summer clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'summer clothes', 3, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Down vest', 'summer clothes', 4, 'M', 'CUSTOM', 27);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'summer clothes', 4, 'M', 'CUSTOM', 235);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Pantsuit', 'winter clothes', 4, 'F', 'CUSTOM', 134);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'winter clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'winter clothes', 4, 'M', 'CUSTOM', 285);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'summer clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'winter clothes', 4, 'F', 'CUSTOM', 75);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'autumn clothes', 3, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'autumn clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'winter clothes', 2, 'M', 'CUSTOM', 237);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Socks', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'winter clothes', 5, 'M', 'CUSTOM', 125);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'summer clothes', 1, 'F', 'CUSTOM', 47);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'summer clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Pantsuit', 'summer clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Socks', 'autumn clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'autumn clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Leggings', 'summer clothes', 1, 'M', 'CUSTOM', 114);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Socks', 'autumn clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Scarf', 'autumn clothes', 2, 'F', 'CUSTOM', 79);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'summer clothes', 5, 'F', 'CUSTOM', 135);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Scarf', 'autumn clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'autumn clothes', 3, 'M', 'CUSTOM', 105);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'winter clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'autumn clothes', 2, 'M', 'CUSTOM', 53);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Leggings', 'summer clothes', 1, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'winter clothes', 3, 'F', 'CUSTOM', 292);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'summer clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'winter clothes', 3, 'M', 'CUSTOM', 171);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Leggings', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'summer clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'winter clothes', 2, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'autumn clothes', 3, 'F', 'CUSTOM', 54);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'summer clothes', 1, 'F', 'CUSTOM', 56);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'autumn clothes', 5, 'M', 'CUSTOM', 123);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'autumn clothes', 1, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'autumn clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'winter clothes', 4, 'F', 'CUSTOM', 224);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Scarf', 'summer clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'summer clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'winter clothes', 3, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'autumn clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cropped sweaters', 'autumn clothes', 5, 'F', 'CUSTOM', 131);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Gloves', 'summer clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Gloves', 'autumn clothes', 5, 'F', 'CUSTOM', 36);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'winter clothes', 4, 'F', 'CUSTOM', 42);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'autumn clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'summer clothes', 1, 'M', 'CUSTOM', 223);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Down vest', 'winter clothes', 1, 'F', 'CUSTOM', 69);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'autumn clothes', 3, 'F', 'CUSTOM', 246);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'autumn clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Hawaiian shirt', 'summer clothes', 5, 'M', 'CUSTOM', 96);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'autumn clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Socks', 'winter clothes', 5, 'M', 'CUSTOM', 296);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'winter clothes', 1, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'winter clothes', 2, 'M', 'CUSTOM', 21);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'summer clothes', 2, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Hawaiian shirt', 'autumn clothes', 2, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Scarf', 'summer clothes', 3, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Scarf', 'summer clothes', 1, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Pantsuit', 'winter clothes', 4, 'F', 'CUSTOM', 298);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Mittens', 'autumn clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'winter clothes', 2, 'F', 'CUSTOM', 240);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Leggings', 'autumn clothes', 3, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'summer clothes', 4, 'F', 'CUSTOM', 170);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'winter clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'summer clothes', 3, 'F', 'CUSTOM', 153);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'autumn clothes', 2, 'M', 'CUSTOM', 201);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'autumn clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Hawaiian shirt', 'winter clothes', 4, 'F', 'CUSTOM', 117);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Pantsuit', 'winter clothes', 5, 'M', 'CUSTOM', 58);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cropped sweaters', 'summer clothes', 5, 'M', 'CUSTOM', 227);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'summer clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'winter clothes', 5, 'M', 'CUSTOM', 128);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'summer clothes', 5, 'F', 'CUSTOM', 168);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dark-wash jeans', 'summer clothes', 5, 'M', 'CUSTOM', 195);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Down vest', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'summer clothes', 4, 'M', 'CUSTOM', 209);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Singlet', 'summer clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coat', 'summer clothes', 2, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'winter clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'winter clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'summer clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Leggings', 'summer clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Singlet', 'winter clothes', 5, 'F', 'CUSTOM', 148);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Hawaiian shirt', 'winter clothes', 1, 'F', 'CUSTOM', 63);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Scarf', 'autumn clothes', 5, 'M', 'CUSTOM', 123);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Pantsuit', 'winter clothes', 1, 'M', 'CUSTOM', 248);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'summer clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Socks', 'autumn clothes', 2, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Trench coats', 'winter clothes', 4, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'autumn clothes', 4, 'F', 'CUSTOM', 41);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Dress', 'winter clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'autumn clothes', 4, 'M', 'CUSTOM', 9);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Down vest', 'winter clothes', 2, 'F', 'CUSTOM', 103);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('wrap coat', 'autumn clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Fleece jacket', 'winter clothes', 5, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'summer clothes', 3, 'F', 'CUSTOM', 293);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'summer clothes', 1, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('T-shirt', 'summer clothes', 3, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Wool trousers', 'summer clothes', 5, 'F', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Gloves', 'winter clothes', 1, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Mittens', 'summer clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Cap', 'winter clothes', 4, 'M', 'DEFAULT', NULL);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Black cashmere', 'autumn clothes', 2, 'F', 'CUSTOM', 138);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Hawaiian shirt', 'autumn clothes', 5, 'M', 'CUSTOM', 131);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'autumn clothes', 3, 'M', 'CUSTOM', 111);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Gloves', 'summer clothes', 1, 'M', 'CUSTOM', 215);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Leggings', 'summer clothes', 2, 'M', 'CUSTOM', 28);
insert into clothes (type, description, layer_number, gender, category, id_user) values ('Sweater', 'summer clothes', 1, 'F', 'DEFAULT', NULL);
